### ISSUE TITLE
Open API 3.0 | throws dangling reference exception

### ISSUE THREAD

**Issue by SrinivasanTarget** [bjansen/swagger-schema-validator#7] opened 2020-04-30 05:30 UTC
Schema has internal references in definition pointers. 

```
com.github.fge.jsonschema.core.exceptions.JsonReferenceException: fatal: danglingRef
    level: "fatal"


	at com.github.fge.jsonschema.main.JsonValidator.buildJsonSchema(JsonValidator.java:190)
	at com.github.fge.jsonschema.main.JsonSchemaFactory.getJsonSchema(JsonSchemaFactory.java:205)
	at com.github.bjansen.ssv.SwaggerValidator.getSchema(SwaggerValidator.java:153)
	at com.github.bjansen.ssv.SwaggerValidator.validate(SwaggerValidator.java:116)
	at com.github.bjansen.ssv.SwaggerValidator.validate(SwaggerValidator.java:102)
	at com.github.bjansen.ssv.SwaggerValidator.validate(SwaggerValidator.java:95)
	at com.github.bjansen.ssv.SwaggerValidator.validate(SwaggerValidator.java:83)
```

**Comment by bjansen** [comment] 2020-04-30 09:21
Hi, this library is not meant to be used with Open API v3 definitions, only Swagger v2. That might explain your error.

**Comment by bjansen** [comment] 2020-07-19 18:45
Actually it looks like a duplicate of #11, it occurs when you pass an invalid definition pointer:

```
validator.validate(myJsonDoc, "/definitions/Blablabla_I_Dont_Exist")
```

**Closed** 2020-07-19 18:46 UTC
